force-app/main/default/objects/Create_Case__e/Create_Case__e.object-meta.xml
<CustomObject>
    <description>This platform event will create a new case</description>
    <label>Create Case</label>
    <pluralLabel>Create Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Create_Case__e/fields/Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Owner_Id__c</fullName>
    <label>Owner Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CasePETriggerUtils.cls
public with sharing class CasePETriggerUtils {
    public static void createCase(List<Create_Case__e> lstCases) {
        List<Case> casesToCreate = new List<Case>();
    
        for (Create_Case__e event : lstCases) {
            Case newCase = new Case(
                Subject = 'High Priority Monitor Alert',
                Description = 'This case was created because a Monitor has a High priority.',
                Priority = 'High',
                AccountId = event.Record_Id__c,
                ownerId = event.Owner_Id__c
            );
            
            casesToCreate.add(newCase);
        }
        
        if (!casesToCreate.isEmpty()) {
            try {
                insert casesToCreate;
            } catch (DmlException e) {
                // create records on Log__c object or send alert to admins
            }
        }
    }
}