force-app/main/default/objects/Account/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Create_Case__e/Create_Case__e.object-meta.xml
<CustomObject>
    <description>This platform event will create a new case</description>
    <label>Create Case</label>
    <pluralLabel>Create Cases</pluralLabel>
</CustomObject>

force-app/main/default/objects/Create_Case__e/fields/Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Owner_Id__c</fullName>
    <label>Owner Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTriggerUtils.cls
public with sharing class AccountTriggerUtils {
    public static String queueName = 'Support';
    public static Group queue = [SELECT Id FROM Group WHERE Type = 'Queue' AND Name = :queueName LIMIT 1];

    public static void firePlatformEvent(List<Account> lstAcc) {
        List<Create_Case__e> eventsToPublish = new List<Create_Case__e>();
        
        for (Account acc : lstAcc) {
            if (acc.Risk__c == 'High') {
                Create_Case__e newEvent = new Create_Case__e(
                    Record_Id__c = acc.Id,
                    Owner_Id__c = queue.Id
                );
                
                eventsToPublish.add(newEvent);
            }
        }
        
        if (!eventsToPublish.isEmpty()) {
            List<Database.SaveResult> results = EventBus.publish(eventsToPublish);
            
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()) {
                    // create records on Log__c object or send alert to admins (depends on company strategy)
                }
            }
        }
    }
}